version: '3.12.12'

services:
  gateway:
    build: .
    expose:
      - 8090
    # ports:
    #   - 8090:8090
    networks:
      - global-network
      
networks:
  global-network:
    external: true